version: '3'
services:
  sqlite3:
    container_name: sqlite_db
    restart: always
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    ports:
      - ${SQLITE_PORT}:9000
    volumes:
      - ./db/:/root/db/
